# Generated by Django 2.0.3 on 2018-03-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.TextField(default='')),
                ('n', models.TextField(default='')),
                ('tel', models.TextField(default='')),
                ('version', models.TextField(default='')),
            ],
        ),
    ]
